rowassist/urls.py
from django.conf.urls import url
from rowassist import views

urlpatterns = [
	url(r'^$', views.home, name='index'),

	url(r'^account/$', views.account, name='account'),
	url(r'^account/sign_in/$', views.sign_in, name='sign_in'),
	url(r'^account/sign_up/$', views.sign_up, name='sign_up'),
	url(r'^account/sign_out/$', views.sign_out, name='sign_out'),
	url(r'^account/sessions/$', views.account_sessions, name='account_sessions'),
	url(r'^account/statistics/$', views.account_statistics, name='account_statistics'),

	url(r'^sessions/$', views.sessions, name='sessions'),
	url(r'^sessions/create/$', views.sessions_create, name='sessions_create'),
	url(r'^sessions/close/$', views.sessions_close, name='sessions_close'),
	url(r'^sessions/edit/$', views.sessions_edit, name='sessions_edit'),
	url(r'^sessions/view/$', views.sessions_view, name='sessions_view'),
	url(r'^session/view/interval/$', views.sessions_view_interval, name="sessions_view_interval"),
	url(r'^sessions/view/enter/$', views.sessions_enter, name='sessions_enter'),


	url(r'^club/create/$', views.create_club, name='create_club'),
	url(r'^club/join/$', views.join_club, name='join_club'),
	url(r'^club/join/confirm/$', views.join_club_confirm, name='join_club_confirm'),
	url(r'^club/join/cancel/$', views.join_club_cancel, name='join_club_cancel'),
	url(r'^club/leave/$', views.leave_club, name='leave_club'),
	url(r'^club/leave/confirm$', views.leave_club_confirm, name='leave_club_confirm'),
	url(r'^club/approve_member/$', views.approve_member, name='approve_member'),
	url(r'^club/approve_member/accept$', views.approve_member_accept, name='approve_member_accept'),
	url(r'^club/approve_member/reject$', views.approve_member_reject, name='approve_member_reject'),


]

wad2_team_project/urls.py
from django.conf.urls import url
from django.contrib import admin
#
from rowassist import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),
	
    url(r'^$', views.index, name='index'),

    url(r'^account/$', views.account, name='account'),
    url(r'^account/sign_in/$', views.sign_in, name='sign_in'),
    url(r'^account/sign_up/$', views.sign_up, name='sign_up'),
    url(r'^account/sign_out/$', views.sign_out, name='sign_out'),

    url(r'^sessions/$', views.sessions, name='sessions'),
    url(r'^sessions/create/$', views.sessions_create, name='sessions_create'),
    url(r'^sessions/close/$', views.sessions_close, name='sessions_close'),
    url(r'^sessions/edit/$', views.sessions_edit, name='sessions_edit'),
    url(r'^sessions/view/$', views.sessions_view, name='sessions_view'),
    url(r'^session/view/interval/$', views.sessions_view_interval, name="sessions_view_interval"),
    url(r'^sessions/view/enter/$', views.sessions_enter, name='sessions_enter'),

    url(r'^club/$', views.club, name='club'),
    url(r'^club/create/$', views.create_club, name='create_club'),
    url(r'^club/join/$', views.join_club, name='join_club'),
    url(r'^club/join/confirm/$', views.join_club_confirm, name='join_club_confirm'),
    url(r'^club/join/cancel/$', views.join_club_cancel, name='join_club_cancel'),
    url(r'^club/leave/$', views.leave_club, name='leave_club'),
    url(r'^club/leave/confirm$', views.leave_club_confirm, name='leave_club_confirm'),
    url(r'^club/approve_member/$', views.approve_member, name='approve_member'),
    url(r'^club/approve_member/accept$', views.approve_member_accept, name='approve_member_accept'),
    url(r'^club/approve_member/reject$', views.approve_member_reject, name='approve_member_reject'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rowassist/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


class Club(models.Model):
	name = models.CharField(max_length=128, unique=True)
	url = models.URLField(blank=True, null=True)
	short_name = models.CharField(max_length=128, unique=True)
    
	def __str__(self): # For Python 2, use __unicode__ too
		return self.name


class Athlete(models.Model):
	user = models.OneToOneField(User)
	is_coach = models.BooleanField()
	User._meta.get_field('email')._unique = True
	picture = models.ImageField(upload_to='profile_images', blank=True)
	club = models.ForeignKey(Club, blank = True, null = True, on_delete=models.SET_NULL, related_name="ApprovedClub")
	requested_club = models.ForeignKey(Club, blank = True, null = True, on_delete=models.SET_NULL, related_name="RequestedClub")


	#def save(self, *args, **kwargs):
	#	self.slug = slugify(self.email)
	#	super(Category, self).save(*args, **kwargs)
	
	class Meta:
		verbose_name_plural = 'athletes'

	def __str__(self): # For Python 2, use __unicode__ too
		return self.user.get_username()		

	def fullname(self):
		return self.user.first_name + " " + self.user.last_name
		

class Session(models.Model):
	types = (
		('S', 'Single interval'),
		('F', 'Fixed interval'),
		('V', 'Variable interval'),
	)
	club = models.ForeignKey(Club)
	type = models.CharField(max_length=1, choices=types)  # enum
	date = models.DateField()
	description = models.TextField(blank=True, null=True)
	name = models.TextField()

	distance = models.IntegerField(blank=True, null=True)
	time = models.TimeField(blank=True, null=True)
	rate = models.IntegerField(blank=True, null=True)
	rest = models.TimeField(blank=True, null=True)
	intervalNo = models.IntegerField(blank=True, null=True)

	isActive = models.BooleanField(default=True)

	def __str__(self):
		return self.name
	
	
class SessionInterval(models.Model):
	session = models.ForeignKey(Session)
	intervalNo = models.IntegerField(primary_key=True)

	distance = models.IntegerField(blank=True, null=True)
	time = models.TimeField(blank=True, null=True)
	rate = models.IntegerField(blank=True, null=True)
	rest = models.TimeField(blank=True, null=True)

	class Meta:
		unique_together = (('session', 'intervalNo'),)

	def __str__(self):
		return self.session.name + ", " +  str(self.intervalNo)

class SessionEntry(models.Model):
	session = models.ForeignKey(Session, blank=False, null=False)
	athlete = models.ForeignKey(Athlete, blank=False, null=False)

	types = (
		('S', 'Single interval'),
		('F', 'Fixed interval'),
		('V', 'Variable interval'),
	)
	type = models.CharField(max_length=1, choices=types)  # enum
	date = models.DateField(blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	name = models.TextField(blank=True, null=True)
	
	distance = models.IntegerField(blank=True, null=True)
	time = models.TimeField(blank=True, null=True)
	rate = models.IntegerField(blank=True, null=True)
	rest = models.TimeField(blank=True, null=True)
	intervalNo = models.IntegerField(blank=True, null=True)


	def __str__(self):
		return self.session.name + ", " + self.athlete.user.first_name
	
	
class SessionEntryInterval(models.Model):
	session_entry = models.ForeignKey(SessionEntry)
	intervalNo = models.IntegerField(primary_key=True)

	distance = models.PositiveIntegerField(blank=True, null=True)  # in metres
	time = models.DurationField(blank=True, null=True)
	strokes_per_minute = models.PositiveIntegerField(blank=True, null=True)
	rest = models.TimeField(blank=True, null=True)

	
	class Meta:
		unique_together = (('session_entry', 'intervalNo'),)

	def __str__(self):
		return self.session_entry.session.name + ", " +  str(self.intervalNo)

rowassist/views.py
from django.shortcuts import render
from rowassist.forms import UserForm, UserProfileForm, AccountForm, CreateSessionForm, CreateSessionIntervalForm, AddSessionEntryIntervalForm, AddSessionEntryForm
from rowassist.models import Athlete, Session, SessionEntry, SessionEntryInterval, SessionInterval
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from rowassist.forms import UserForm, UserProfileForm, CreateClubForm, JoinClubForm
from rowassist.models import Club, Athlete, User
from rowassist.decorators import coach_requried
from django.http import JsonResponse
from django.forms.formsets import formset_factory


# Create your views here.

@login_required
def index(request):
    user_sessions = SessionEntry.objects.filter(athlete = request.user.athlete)
    context_dict = {'user_sessions': user_sessions}
    return render(request, 'rowassist/index.html', context_dict)


#------account views------
@login_required
def account(request):
    user = request.user
    user_sessions = SessionEntry.objects.filter(athlete=user.athlete)

    context_dict = {'user_sessions': user_sessions} 
    response = render(request, 'rowassist/account.html', context_dict)
    return response

def sign_in(request):
    error_message = ''
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('account'))
            else:
                error_message = "Your Rowassist account is disabled."
        else:
            error_message = "Invalid Username or Password."

    return render(request, 'rowassist/sign_in.html', {'error_message': error_message})


def sign_up(request):
    error_message = {}
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            # save the users data
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            # save the extra data
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            # log the new user in
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            login(request, user)
            return HttpResponseRedirect(reverse('index'))


        else:
            error_message = {**user_form.errors, **profile_form.errors}
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    return render(request, 'rowassist/sign_up.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'error_message': error_message})


@login_required
def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


#------session views------
@login_required
def sessions(request):
    user = request.user
    club_sessions = Session.objects.filter(club=user.athlete.club)

    active_sessions = club_sessions.filter(isActive=True)
    previous_sessions = club_sessions.filter(isActive=False)

    context_dict = {'active_sessions': active_sessions, 'previous_sessions': previous_sessions}

    response = render(request, 'rowassist/sessions.html', context_dict)
    return response


@login_required
@coach_requried
def sessions_create(request):
    error_message = {}

    intervalFormSet = formset_factory(CreateSessionIntervalForm, min_num=1, extra=0)

    if request.method == 'POST':
        create_session_form = CreateSessionForm(data=request.POST)
        create_interval_form = intervalFormSet(data=request.POST)

        if create_session_form.is_valid() and create_interval_form.is_valid():
            session = create_session_form.save(commit=False)

            session.club = request.user.athlete.club
            session.save()

            if  create_session_form.data['type'] == 'V':
                for counter, intervalForm in enumerate(create_interval_form):
                    distance = intervalForm.cleaned_data.get('distance')
                    time = intervalForm.cleaned_data.get('time')
                    rest = intervalForm.cleaned_data.get('rest')
                    rate = intervalForm.cleaned_data.get('rate')

                    error_message = distance

                    if (intervalForm.is_valid()):
                        interval = intervalForm.save(commit=False)
                        interval.session = session
                        interval.intervalNo = counter
                        interval.save()

            return HttpResponseRedirect(reverse('sessions_create'))
        else:
            error_message = create_session_form.errors
            #error_message = {**create_session_form.errors, **create_interval_form.errors}

    return render(request, 'rowassist/sessions_create.html', {'sessionForm': CreateSessionForm(), 'intervalFormSet': intervalFormSet, 'error_message': error_message})

@login_required
@coach_requried
def sessions_close(request):
    sess_id = request.GET.get('id', '')
    session = Session.objects.get(id=sess_id)

    if (session.club == request.user.athlete.club):
        session.isActive = False
        session.save()

    return HttpResponseRedirect(reverse('sessions'))

@login_required
def sessions_edit(request):
    response = render(request, 'rowassist/sessions_edit.html')
    return response


@login_required
def sessions_view(request):
    sess_id = request.GET.get('id', '')
    target_session = Session.objects.get(id=sess_id)
    if (target_session.club == request.user.athlete.club):

        session_entries = SessionEntry.objects.filter(session=target_session)

        context_dict = {'session_entries': session_entries, 'target_session':target_session}

        response = render(request, 'rowassist/sessions_view.html', context=context_dict)
        return response

    return HttpResponseRedirect(reverse('account'))


@login_required
def sessions_view_interval(request):
    session_entry_id = request.GET.get('seid', '')
    session_entry = SessionEntry.objects.get(id=session_entry_id)
    if session_entry.session.club == request.user.athlete.club:
        session_entry_intervals = SessionEntryInterval.objects.filter(session_entry=session_entry)

        context_dict = {'intervals': session_entry_intervals}

        return render(request, 'rowassist/sessions_view_interval.html', context=context_dict)

    return HttpResponseRedirect(reverse('account')) 

@login_required
def sessions_enter(request):
    sess_id = request.GET.get("id", "")

    session = Session.objects.get(id=sess_id)
    user = request.user

    user_club = user.athlete.club

    if session.type != "V":
        interval_no = 1 if session.intervalNo is None else session.intervalNo
        distance_fixed = session.time is None
    else:
        session_intervals = SessionInterval.objects.filter(session=session)
        interval_no = len(session_intervals)

        distance_fixed = []

        for session_interval in session_intervals:
            distance_fixed.append(session_interval is None)

    intervalFormSet = formset_factory(AddSessionEntryIntervalForm, min_num=interval_no, max_num=interval_no, extra=0)

    error_message = ""

    if session.club != user_club:
        return HttpResponseRedirect(reverse('account'))
    else:
        if request.method == 'POST':
            interval_form = intervalFormSet(data=request.POST)
            if(interval_form.is_valid()):
                print(interval_form)
                session_entry = SessionEntry.objects.get_or_create(session = session, athlete=user.athlete)[0]
                for counter, intervalForm in enumerate(interval_form):
                    distance = intervalForm.cleaned_data.get('distance')
                    time = intervalForm.cleaned_data.get('time')
                    rate = intervalForm.cleaned_data.get('rate')

                    if(intervalForm.is_valid()):
                        interval = intervalForm.save(commit=False)
                        interval.session_entry = session_entry
                        interval.intervalNo = counter
                        interval.save()
                return HttpResponseRedirect(reverse('sessions'))
            else:
                error_message = interval_form.errors


    return render(request, 'rowassist/sessions_enter.html',
                  {'sessionForm': AddSessionEntryForm(), 'intervalFormSet': intervalFormSet,
                   'session': session,
                   'error_message': error_message, 'interval_no': interval_no,
                   'distance_fixed': distance_fixed})


@login_required
@coach_requried
def create_club(request):
    error_message = {}
    create_club_form = CreateClubForm()

    if request.method == 'POST':
        club_form = CreateClubForm(data=request.POST)

        if club_form.is_valid():
            # save new club
            club_form.save(commit=True)

            # update curent user's club
            name = club_form.data['name']
            request.user.athlete.club = Club.objects.get(name=name)
            request.user.athlete.save()

            # return user to account page
            return HttpResponseRedirect(reverse('account'))
        else:
            error_message = club_form.errors

templates/rowassist/about_us.html
{% extends 'rowassist/base.html' %}

{% block title_block %}
	About Us
{% endblock %}

{% block body_block %}
	the about us page!
{% endblock %}

templates/rowassist/account_sessions.html
{% extends 'rowassist/base.html' %}

{% block title_block %}
	User Sessions
{% endblock %}

{% block body_block %}

    account sessions

{% endblock %}

templates/rowassist/club.html
{% extends 'rowassist/base.html' %}

{% block title_block %}
	Club
{% endblock %}

{% block body_block %}
{% if club %}
	<h3 class="center hide-on-small-only">{{club.name}}</h3>
	<h3 class="center hide-on-med-and-up">{{club.short_name}}</h3>
	<div class="center">

	<h4>Coaches</h4>
	{% for coach in coaches %}
		{{coach.fullname}}<br>
	{% endfor %}

	<h4>Athletes</h4>
	{% for athlete in athletes %}
		{{athlete.fullname}}<br>
	{% endfor %}
	</div>
{% else %}
	<h4 class="center">You have no curent club</h4>
{% endif %}

    <div class="section">
      	<div class="row center">
      		<a class="waves-effect waves-light btn orange" href="{% url 'sessions' %}">View Sessions</a>
   			<a class="waves-effect waves-light btn orange" href="{% url 'sessions_create' %}">Create Session</a>
   			<a class="waves-effect waves-light btn orange" href="{% url 'approve_member' %}">Member request</a>
      	</div>
    </div>


{% endblock %}

templates/rowassist/create_club.html
{% extends 'rowassist/base.html' %}

{% block title_block %}
	Create Club
{% endblock %}

{% block body_block %}
	<h3 class="center">Create Club</h3>
	{% if error_message %}
		<div class="center">
			{% for key, error in error_message.items %}
				<h5>{{ error }}</h5>
			{% endfor %}
		</div>
	{% endif %}

	<form id="create_club_form" method="post" action="{% url 'create_club' %}" enctype="multipart/form-data">
		{% csrf_token %}

		<div class="row">
			<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_name" type="text" name="name" class="validate" maxlength="128" required>
			  	<label for="id_name">Club Name</label> 
			</div>
		</div>

		<div class="row">
			<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_short_name" type="text" name="short_name" class="validate">
			  	<label for="id_short_name">Short Name</label> 
			</div>
		</div>

		<div class="row">
			<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_url" type="url" name="url" class="validate">
			  	<label for="id_url">Website</label> 
			</div>
		</div>

		<div class="row">
			<div class="center">
				<button class="btn waves-effect waves-light orange" type="submit" name="submit">Create Club</button>
			</div>
		</div>
	</form>
{% endblock %}

templates/rowassist/join_club_confirm.html
{% extends 'rowassist/base.html' %}

{% block title_block %}
	Confirm Join Club
{% endblock %}

{% block body_block %}
	<h3 class="center">Join Club</h3>
	<div class="row">
		<div class="col s12 l4 offset-l4">
			<p class="center">You have succesfuly requested to join {{club}}. You will be able to record sessions once a coach has approved you.</p>
		</div>
	</div>


	<div class="center">
  		<a href="{% url 'join_club_cancel' %}" class="waves-effect waves-light btn orange">Cencel Request</a>
	</div>
{% endblock %}

templates/rowassist/sessions_create.html
{% extends 'rowassist/base.html' %}

{% block title_block %}
	Add Session
{% endblock %}

{% block body_block %}
	<h3 class="center">Create Session</h3>
	{% if error_message %}
		{{error_message}}
	{% endif %}

	<form id="create_session_form" method="post" action="{% url 'sessions_create' %}" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="row">
    		<div class="input-field col s12 l4 offset-l4">
    			<input id="id_name" type="text"  name="name" class="validate" required>
			  	<label for="id_name">Session Name</label>
    		</div>
    	</div>

    	<div class="row">
    		<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_date" type="text"  name="date" class="datepicker" required>
			  	<label for="id_date">Date</label>
			</div>
		</div>

		<div class="row">
			<div class="col s12">
			<ul id="tabs-swipe-demo" class="tabs center">
				<li class="tab col s4 l3 offset-l2"><a id="single">Single Interval</a></li>
				<li class="tab col s4 l2"><a id="fixed">Fixed Interval</a></li>
				<li class="tab col s4 l3"><a id="variable">Variable Interval</a></li>
			</ul>
			</div>
		</div>

		<div class="row">
			<div class="col s12 l4 offset-l4">
				<div class="divider">
				</div>
			</div>
		</div>

		<div class="row">
    		<div class="col s4 l2 offset-l2 center">
    			<p>
				    <input name="distanceOrTime" type="radio" id="distanceRadio" class="distanceOrTimeRadio" value="0" checked />
				    <label for="distanceRadio">By Distance</label>
				</p>

				<p>
				    <input name="distanceOrTime" type="radio" id="timeRadio"  class="distanceOrTimeRadio" value="1"/>
				    <label for="timeRadio">By Time</label>
				</p>
			</div>

			<div class="input-field col s4 l2 div_distance">
			  	<input id="id_distance" type="number" name="distance" class="validate distance_input">
			  	<label for="id_distance">Distance</label> 
			</div>

			<div class="input-field col s4 l2 hide div_time">
			  	<input id="id_time" type="text" name="time" class="validate time_input">
			  	<label for="id_time">Time</label>
			</div>

			<div class="input-field col s4 l2">
			  	<input id="id_rate" type="number"  name="rate" class="validate">
			  	<label for="id_rate">Rate</label>
			</div>


    	</div> 

    	<div class="row hide" id="fixedInterval">
			<div class="input-field col s12 l2 offset-l4">
			  	<input id="id_intervalNo" type="number"  name="intervalNo" class="validate">
			  	<label for="id_intervalNo">Number of intervals</label>
			</div>

			<div class="input-field col s12 l2">
			  	<input id="id_rest" type="text"  name="rest" class="validate">
			  	<label for="id_rest">Rest time</label>
			</div>
		</div>

	    <div class="row">
			<div class="col s12 l8 offset-l2">
				<div class="divider">
				</div>
			</div>
		</div>

		<div class="variableForm">
			{{intervalFormSet.management_form }}
			{% for interval in intervalFormSet %}
				<div class="link-formset row">

					<div class="col s4 l2 offset-l2 center">
						<p>
					    	<input name="distanceOrTime{{interval.distance.id_for_label}}" type="radio" id="distanceRadio{{interval.distance.id_for_label}}" class="distanceOrTimeRadio" value="0" checked/>
					    	<label for="distanceRadio{{interval.distance.id_for_label}}">By Distance</label>
					    </p>
					    <p>
							<input name="distanceOrTime{{interval.distance.id_for_label}}" type="radio" id="timeRadio{{interval.distance.id_for_label}}" class="distanceOrTimeRadio" value="1"/>
							<label for="timeRadio{{interval.distance.id_for_label}}">By Time</label>
					    </p>
					</div>

					<div class="input-field col s2 l2 div_distance">
						<input type="number" name="{{interval.distance.id_for_label|slice:'3:'}}" id="{{interval.distance.id_for_label}}">
						<label for="{{interval.distance.id_for_label}}">Distance</label>
					</div>

					<div class="input-field col s2 l2 hide div_time">
						<input type="text" name="{{interval.time.id_for_label|slice:'3:'}}" id="{{interval.time.id_for_label}}">
						<label for="{{interval.time.id_for_label}}">Time</label>
					</div>

					<div class="input-field col s2 l2">
						<input type="number" name="{{interval.rate.id_for_label|slice:'3:'}}" id="{{interval.rate.id_for_label}}">
						<label for="{{interval.rate.id_for_label}}">Rate</label>
					</div>

					<div class="input-field col s2 l2">
						<input type="text" name="{{interval.rest.id_for_label|slice:'3:'}}" id="{{interval.rest.id_for_label}}">
						<label for="{{interval.rest.id_for_label}}">Rest</label>
					</div>
				</div>
			{% endfor %}
		</div>


		<div class="row" id="div_id_description">
    		<div class="input-field col s12 l8 offset-l2">
    			<textarea id="id_description" class="materialize-textarea" name="description"></textarea>
    			<label for="id_description">Session Description (Comments)</label>
    		</div>
    	</div>

		<div class="row">
			<div class="center">
				<input type="text" id="id_type" class="hide" name="type">
				<button class="btn waves-effect waves-light orange" type="submit" name="submit">Create Session</button>
			</div>
		</div>
	</form>

{% endblock %}

{% block javascript%}
	<script>
		$(document).ready(function() {
			var IC = 0;
			$("#id_type").val("S");
			$(".variableForm").addClass('hide');


			$('#single').click(function() {
				$("#fixedInterval").addClass('hide');
				$(".variableForm").addClass('hide');
				$("#id_type").val("S");
			})

			$('#fixed').click(function() {
				$("#fixedInterval").removeClass('hide');
				$(".variableForm").addClass('hide');
				$("#id_type").val("F");
			})

			$('#variable').click(function() {
				$("#fixedInterval").addClass('hide');
				$(".variableForm").removeClass('hide');
				$("#id_type").val("V");
			})
  		})

  		$('.link-formset').formset({
	        addText: '<i class="Tiny material-icons">add</i>',
	        deleteText: '<i class="Tiny material-icons">remove</i>'
	    });

	    $(document).on('click', '.distanceOrTimeRadio', function() { 
			if ($(this).val() == 1){
				
				$(this).parent().parent().parent().find('.div_time').removeClass("hide");
				$(this).parent().parent().parent().find('.div_distance').addClass("hide");
				$(this).parent().parent().parent().find('.distance_input').val("");
			} else {
				$(this).parent().parent().parent().find('.div_time').addClass("hide");
				$(this).parent().parent().parent().find('.div_distance').removeClass("hide");
				$(this).parent().parent().parent().find('.time_input').val("");
			}
		})
	</script>
{% endblock %}

templates/rowassist/sign_up.html
{% extends 'rowassist/base.html' %}
{% load staticfiles %}

{% block title_block %}
Register
{% endblock %}

{% block body_block %}
	<h3 class="center">Sign Up</h3>

	{% if error_message %}
		<div class="center">
			{% for key, error in error_message.items %}
				<h5>{{ error }}</h5>
			{% endfor %}
		</div>
	{% endif %}


	<form id="user_form" method="post" action="{% url 'sign_up' %}" enctype="multipart/form-data">

		{% csrf_token %}

    	<div class="row">
    		<div class="input-field col s12 l2 offset-l4">
    			<input id="id_first_name" type="text" name="first_name" class="validate" required>
    			<label for="id_first_name">First Name</label>
    		</div>

    		<div class="input-field col s12 l2">
    			<input id="id_last_name" type="text" name="last_name" class="validate" required>
    			<label for="id_last_name">Last Name</label>
    		</div>
    	</div>

		<div class="row">
			<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_username" type="text" name="username"class="validate" required>
			  	<label for="id_username">Username</label> 
			</div>
		</div>

		<div class="row">
			<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_email" type="email" name="email"class="validate" required>
			  	<label for="id_email">Email</label> 
			</div>
		</div>

		<div class="row">
			<div class="input-field col s12 l4 offset-l4">
			  	<input id="id_password" type="password"  name="password" class="validate" required>
			  	<label for="id_password">Password</label>
			</div>
		</div>

		<div class="row">
			<div class="file-field input-field col s12 l4 offset-l4">
				<div class="btn orange">
					<span>Add a Profile Picture</span>
					<input type="file" name="picture" id="id_picture">
				</div>
					<div class="file-path-wrapper">
					<input class="file-path validate" type="text">
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col s12 l4 offset-l4 center">
				<input type="checkbox" id="id_is_coach" name="is_coach"/>
  				<label for="id_is_coach">Are you a coach?</label>
			</div>
		</div>

		<div class="row">
			<div class="center">
				<button class="btn waves-effect waves-light orange" type="submit" name="submit">Create Account</button>
			</div>
		</div>
		

	</form>
{% endblock %}